### ISSUE TITLE
Defining behavior if lshw segfaults

### ISSUE THREAD

**Issue by ErwanAliasr1** [enovance/hardware#3]
As per issue #245 on edeploy, if lshw segaults, we are no more pushing information about NICs and some other components.

In the SpinalStack case, that's a big issue as it breaks upload.py which requires mac addr & so.
In the wrangling case, that will surely have impacts too.

I would suggest stopping everything and report a failure if we don't have any output from lshw.

What do you think ?

**Comment by nplanel** [comment]
cmd() function helper already generate a return like this (139, 'whatever program output\n')

139 is -11 in int8, returned internally by the wait() call ; By convention wait() return -signal_number as returncode.

So I think is a good idea to change the logic behavior in cmd()

if -(excpt.returncode & 0x7f) == -11: /* SIGSEGV */
      print "a nice message, like we suspect receiving a segfault from the command cmdline ...."
      print "the program cannot run normally .... parachute deployed !"
      os.abort()

**Comment by fredericlepied** [comment]
@nplanel I prefer we don't change cmd as some commands are optional. We need to handle the case of lshw in a special way because that's the mandatory part and we need to exit only on this one.
